# Generated by Django 5.2.17 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_teams', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization')),
                ('default_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_services', to='service_catalogue.serviceteam')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='organizations.organizationmembership')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='service_catalogue.serviceteam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='serviceteam',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_service_team_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='serviceteam',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_service_team_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_service_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_service_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'membership'), name='unique_member_per_team'),
        ),
    ]
