# Generated by Django 5.2.17 on 2026-09-19 19:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('service_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('current_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_TRIAGE', 'Pending triage'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_REQUESTER', 'Waiting for requester'), ('RESOLVED', 'Resolved')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_catalogue.serviceteam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='organizations.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='organizations.organizationmembership')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_catalogue.service')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('PENDING_TRIAGE', 'Pending triage'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_REQUESTER', 'Waiting for requester'), ('RESOLVED', 'Resolved')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_TRIAGE', 'Pending triage'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_REQUESTER', 'Waiting for requester'), ('RESOLVED', 'Resolved')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to='organizations.organizationmembership')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cases.servicerequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
